import type { Metadata } from "next";
import "../globals.css";
import { Navbar } from "@/components/molecules/Navbar/Navbar";
import s from '../global.module.css'
import ProtectedRoute from '@/components/ProtectedRoute'
import InfoClient from "@/components/molecules/InfoClient/InfoClient";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ProtectedRoute >
      <html lang="en">
        <body
          className={s.body}
        >
          <main className={s.background}>
          <Navbar/>
          <div className={s.container}>
            <main className={s.main}>
            <header className={s.header}>
              <h1 className={s.h1}>Seccion</h1>
              <InfoClient />
            </header>
            {children}
            </main>
          </div>
          </main>
        </body>
      </html>
    </ProtectedRoute>
  );
}
