import type { Metadata } from "next";
import "../globals.css";
import { Navbar } from "@/components";
import s from '../global.module.css'
import { PersonFillIcon,SignOutIcon } from '@primer/octicons-react'
import ProtectedRoute from '@/components/ProtectedRoute'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ProtectedRoute >
      <html lang="en">
        <body
          className={`antialiased font-roboto`}
        >
          <main className={s.background}>
          <Navbar/>
          <div className={s.container}>
            <main className={s.main}>
            <header className={s.header}>
              <h1 className={s.h1}>Sección</h1>
              <div className={s.contentUser}>
                <div>
                  <PersonFillIcon size={24} />
                  <span>Noé Aviles</span>
                </div>
                <div>
                  <SignOutIcon size={24} className={s.iconSinOut} />
                </div>
              </div>
            </header>
            {children}
            </main>
          </div>
          </main>
        </body>
      </html>
    </ProtectedRoute>
  );
}
